language: c
os:
  - linux
  - osx

compiler:
  - gcc

install:
  - set -e
  - curl https://dist.libuv.org/dist/v1.14.0/libuv-v1.14.0.tar.gz -o $(pwd)/libuv-v1.14.0.tar.gz
  - tar -xvf libuv-v1.14.0.tar.gz 
  - cd libuv-v1.14.0
  - sh autogen.sh
  - ./configure --prefix=/opt/libuv
  - make 
  - sudo make install
  - cd ..
  - git clone -b devel --depth 1 https://github.com/nim-lang/Nim.git
  - cd Nim
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - bin/nim c koch
  - ./koch boot -d:release
  - ./koch nimble
  - export PATH=$(pwd)/bin:$PATH
  - cd ..
  - nimble install httpkit
  #- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then rvm get head; fi # fix osx ``shell_session_update: command not found``

script:
  - nim test
  
  
